### ISSUE TITLE
Can't create CredentialManager instance

### ISSUE THREAD

**Issue by tranvantung95** [tdcolvin/ExampleCredentialSignIn#1]
I flow your guide 
[Jetpack Credential Manager](https://proandroiddev.com/using-jetpack-credential-manager-to-save-and-retrieve-passwords-in-app-c8d2793f5c5c)
But can't init CredentialManager.
Code 

> private val credentialManager by lazy {
       CredentialManager.create(application)
   }
>

I already try with your demo, it same issue.
[Please see  logcat in image](https://i.stack.imgur.com/h5s17.jpg)

**Comment by tdcolvin** [comment]
I suspect you are using an emulator here.
In order to have a CredentialManager to sign in with, you need to use a real device or emulator with Google Play, and in either case you need to be signed in with a Google account. That should solve the issue, please let me know.

**Comment by tranvantung95** [comment]
let me check with real device, because my device run on android 13 and i can't install apk to my device.

**Comment by tdcolvin** [comment]
The code works pre-Android 13. Min SDK is 24

**Comment by tranvantung95** [comment]
I try your example it work.  I write but not use compose. but still fail in step save credential.
Have any settings with project.?
`Credential save error: During save password, found password failure response from one tap 16: Skipping password saving since the user is likely prompted with Android Autofill.-- android.credentials.CreateCredentialException.TYPE_UNKNOWN
                                                                                                    androidx.credentials.exceptions.CreateCredentialUnknownException: During save password, found password failure response from one tap 16: Skipping password saving since the user is likely prompted with Android Autofill.
                                                                                                    	at androidx.credentials.playservices.controllers.CredentialProviderBaseController$Companion.createCredentialExceptionTypeToException$credentials_play_services_auth_release(CredentialProviderBaseController.kt:108)
                                                                                                    	at androidx.credentials.playservices.controllers.CreatePassword.CredentialProviderCreatePasswordController$resultReceiver$1$onReceiveResult$1.invoke(CredentialProviderCreatePasswordController.kt:82)
                                                                                                    	at androidx.credentials.playservices.controllers.CreatePassword.CredentialProviderCreatePasswordController$resultReceiver$1$onReceiveResult$1.invoke(CredentialProviderCreatePasswordController.kt:82)
                                                                                                    	at androidx.credentials.playservices.controllers.CredentialProviderController.maybeReportErrorFromResultReceiver(CredentialProviderController.kt:157)
                                                                                                    	at androidx.credentials.playservices.controllers.CreatePassword.CredentialProviderCreatePasswordController.access$maybeReportErrorFromResultReceiver(CredentialProviderCreatePasswordController.kt:46)
                                                                                                    	at androidx.credentials.playservices.controllers.CreatePassword.CredentialProviderCreatePasswordController$resultReceiver$1.onReceiveResult(CredentialProviderCreatePasswordController.kt:81)
                                                                                                    	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
`

**Comment by tdcolvin** [comment]
Closing this issue as original point is addressed. Second point warrants new issue, created above.
